config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # websocket
  mount ActionCable.server => '/cable'

  # landing page
  root 'home#index'

  # users and authentication
  devise_for :users
  resources :users, only: [:show]

  # spotify user oauth authentication
  get '/auth/spotify/callback', to: 'users#spotify'

  # events management and joining
  resources :events, except: [:index] do
    post 'start_playing', on: :member
    post 'stop_playing', on: :member
    post 'create_new_playlist', on: :member
  end

  get '/:join_code' => 'events#join', :as => :join_events
  post '/join' => 'events#join', :as => :join_events_submit
end

app/models/user.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  spotify_attributes     :text
#

# A registered user of the application
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events

  serialize :spotify_attributes

  # A basic check to verify that there are attributes stored in spotify
  # attributes. We may want to consider a more "reliable" verification
  def user_spotify_authenticated?
    self.spotify_attributes.present? &&
      self.spotify_attributes.key?('credentials') &&
      self.spotify_attributes['credentials'].key?('refresh_token') &&
      self.spotify_attributes['credentials'].key?('token')
  end

  def spotify
    @spotify ||= RSpotify::User.new(self.spotify_attributes)
  end

  def add_to_saved(song)
    track = RSpotify::Track.find(song.uri.sub!('spotify:track:', ''))

    spotify.save_tracks!(Array(track))
  end

  def avatar
    # safely traverse the spotify attributes as there may be fields that don't exist
    self.try(:spotify_attributes).try(:[], 'images').try(:[], 0).try(:[], 'url')
  end

  def display_name
    # safely traverse the spotify attributes as there may be fields that don't exist
    name = self.try(:spotify_attributes).try(:[], 'display_name')

    # If no display name, try to use Spotify username (id)
    name.present? ? name : self.try(:spotify_attributes).try(:[], 'id')
  end

  def spotify_id
    # safely traverse the spotify attributes as there may be fields that don't exist
    self.try(:spotify_attributes).try(:[], 'id')
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true
class UsersController < ApplicationController
  before_action :auth_user

  def show
    @user = User.find(params[:id])
    @events = @user.events
  end

  def spotify
    spotify_user = RSpotify::User.new(request.env['omniauth.auth'])

    if current_user.update!(spotify_attributes: spotify_user.to_hash)
      redirect_to current_user, notice: 'Nice! You have successfully authenticated with Spotify.'
    else
      redirect_to current_user, error: 'Oh snap! Something didn\'t go correctly'
    end
  end

  private

  def auth_user
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/views/users/show.html.haml
.container.container-custom
  .row
    .col-md-12
      %h3
        - if @user.avatar.present?
          = image_tag(@user.avatar, class: 'user__avatar')
        = greeting

      - if @events.empty?
        %p.lead
          It doesn't look like you've created any events. Wanna make one now?
      - else
        %p.lead
          You can view all of your existing events below or
          = link_to 'create a new one', new_event_path
  .row
    - if @events.empty?
      .col-md-4
        .card
          = image_tag('events/1.jpg', class: 'card-img-top')
          .card-block
            %h4.card-title
              Your First Event
            %p.card-text
              Create an event then we can add guests and start on your song queue.
            = link_to new_event_path, class: 'btn btn-primary' do
              Let's Get Started!
    - else
      .col-md-12
        - @events.in_groups_of(3, false).each do |event_group|
          .row
            - event_group.each do |event|
              .col-md-4
                .card
                  = image_tag(event.avatar_image, class: 'card-img-top')
                  .card-block
                    %h4.card-title
                      = event.name
                    %p.card-text
                      = event.description
                    = link_to event_path(event), class: 'btn btn-primary' do
                      View Event