config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # websocket
  mount ActionCable.server => '/cable'

  # landing page
  root 'home#index'

  # users and authentication
  devise_for :users
  resources :users, only: [:show]

  # spotify user oauth authentication
  get '/auth/spotify/callback', to: 'users#spotify'

  # events management and joining
  resources :events, except: [:index] do
    post 'start_playing', on: :member
    post 'stop_playing', on: :member
    post 'create_new_playlist', on: :member
  end

  get '/:join_code' => 'events#join', :as => :join_events
  post '/join' => 'events#join', :as => :join_events_submit
end

app/controllers/home_controller.rb
# frozen_string_literal: true
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.haml
= content_for :alert_class, "alert--cover"

.jumbotron.jumbotron-fluid.jumbotron-custom
  .container
    %h1
      %i.fa.fa-music
      Play This

    %p.lead
      Create a custom playlist for guests at an event to collaborate, suggest
      and vote on the songs to be played.

.container__landing-page
  .container
    .row
      .col-md-12
        %h3
          Were you invited to join an event?

        %p.lead
          Enter the event code here to join:

        = form_for :events, :url => join_events_submit_path, method: :post, html: { class: 'form-inline' } do |f|
          .form-group
            = f.text_field :join_code, autofocus: true, class: 'form-control', placeholder: "Event Code"

          = f.submit 'Go', class: "btn btn-secondary"