config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # websocket
  mount ActionCable.server => '/cable'

  # landing page
  root 'home#index'

  # users and authentication
  devise_for :users
  resources :users, only: [:show]

  # spotify user oauth authentication
  get '/auth/spotify/callback', to: 'users#spotify'

  # events management and joining
  resources :events, except: [:index] do
    post 'start_playing', on: :member
    post 'stop_playing', on: :member
    post 'create_new_playlist', on: :member
  end

  get '/:join_code' => 'events#join', :as => :join_events
  post '/join' => 'events#join', :as => :join_events_submit
end

app/models/event.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: events
#
#  id                  :integer          not null, primary key
#  name                :string           not null
#  description         :text             not null
#  join_code           :string           not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :integer
#  spotify_playlist_id :string
#  currently_playing   :boolean          default(FALSE), not null
#  pnator_enabled      :boolean
#  pnator_danceability :float
#  pnator_energy       :float
#  pnator_popularity   :float
#  pnator_speechiness  :float
#  pnator_happiness    :float
#  image_url           :text
#

# An event or party that multiple users can join
class Event < ApplicationRecord
  JOIN_CODE_LENGTH = 8

  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
  validates :join_code, presence: true, uniqueness: true, length: { minimum: JOIN_CODE_LENGTH }, format: { with: /\A[a-z0-9\-_]+\z/ }

  has_many :songs

  scope :currently_playing, -> { where(currently_playing: true) }

  def placeholder_avatar_image
    # we currently have 5 default images
    "events/#{(id % 4) + 1}.jpg"
  end

  def avatar_image
    self.image_url.present? ? self.image_url : placeholder_avatar_image
  end

  def current_queue
    self.songs.active_queue.ranked
  end

  def can_queue_song?
    current_queue.positive?
  end

  def next_song
    current_queue.first
  end

  def queue_next_song
    # if there is no next song then try to generate some
    unless next_song || !self.pnator_enabled
      apply_pnator(self.user, true, 3)
    end

    # if there wasn't a song left and playlistinator failed
    return true unless next_song
    song = next_song

    auth_user
    spotify_playlist.add_tracks!([song.to_spotify_track])
    song.remove_from_queue
    send_currently_playing

    return true # Spotify didn't error
  end

  def check_queue
    return unless should_queue_next_song?
    queue_next_song
  end

  def channel_name
    "event-#{self.id}"
  end

  def show_current_song?
    self.currently_playing && song_is_playing?
  end

  def currently_playing_song
    self.songs.where.not(queued_at: nil).order(queued_at: :desc).first
  end

  def send_currently_playing(channel: self.channel_name)
    return false unless show_current_song?
    current_song_json = currently_playing_song.as_json
    current_song_json[:time_remaining] = ((currently_playing_song.queued_at + (currently_playing_song.duration / 1000).seconds) - Time.now.utc).in_milliseconds
    ActionCable.server.broadcast channel, action: 'current-song', data: current_song_json
  end

  def apply_pnator(authed_user, bypass_auth, num_songs)
    # You must be the owner and there must be some songs to seed from
    return unless (bypass_auth || (authed_user && self.user == authed_user)) &&
                  self.songs.all.count.positive? && self.pnator_enabled

    seed_tracks = self.songs.last(5).pluck(:uri).map { |uri| uri.split(':')[-1] }
    pnator_popularity = (self.pnator_popularity * 100).round
    recs = RSpotify::Recommendations.generate(limit: num_songs, seed_tracks: seed_tracks,
                                              target_energy: self.pnator_energy,
                                              target_speechiness: self.pnator_speechiness,
                                              target_danceability: self.pnator_danceability,
                                              target_valence: self.pnator_happiness,
                                              target_popularity: pnator_popularity)

    recs.tracks.each do |t|
      next if Song.exists?(uri: t.uri, event: self)

      song = Song.create!(name: t.name, artist: t.artists[0].name, art: t.album.images[0]['url'], duration: t.duration_ms,
                          uri: t.uri, event: self)

      ActionCable.server.broadcast self.channel_name, action: 'add-song', data: song
    end
  end

  def set_join_code
    self.join_code = generate_join_code
  end

  private

  def song_is_playing?
    song = currently_playing_song
    return false unless song.present?
    (song.queued_at + (song.duration / 1000).seconds) >= (Time.now.utc)
  end

  def auth_user
    # TODO(skovy) make this cleaner
    self.user.spotify
  end

  def should_queue_next_song?
    song = currently_playing_song

    # if there are not songs currently playing or played, queue up!
    return true unless song.present?

    (song.queued_at + (song.duration / 1000).seconds) <= (Time.now.utc + 5.seconds)
  end

  def spotify_playlist
    user_id = self.user.spotify_attributes['id']
    playlist_id = self.spotify_playlist_id
    @spotify_playlist ||= RSpotify::Playlist.find(user_id, playlist_id)
  end

  def generate_join_code
    loop do
      token = (0...JOIN_CODE_LENGTH).map { ('a'..'z').to_a[rand(26)] }.join
      break token unless Event.where(join_code: token).exists?
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :start_playing, :stop_playing, :create_new_playlist]
  before_action :authenticate, only: [:show, :edit]
  before_action :authenticate_owner, only: [:edit, :update]

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = Event.new
    @event.set_join_code # initialize the join code to a randomly generated code for the user
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user # the owner

    pnator_setup

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    pnator_setup

    respond_to do |format|
      if @event.save && @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def join
    if join_event_params.present?
      @event = Event.find_by_join_code(join_event_params)

      if @event.present?
        set_join_cookie
        set_user_identifier_cookie
        redirect_to event_path(@event, is_guest: true), notice: "You've sucessfully joined #{@event.name}"
      else
        redirect_to root_path, flash: { error: "Invalid code: #{join_event_params}" }
      end
    else
      redirect_to root_path, flash: { error: 'No join code found' }
    end
  end

  def start_playing
    if create_playlist && queue_first_song && set_playing
      redirect_to @event, notice: 'Sweet! The playlist has started.'
    else
      redirect_to @event, error: 'An error occurred creating the playlist.'
    end
  end

  def stop_playing
    if @event.update(currently_playing: false)
      redirect_to @event, notice: 'Nifty! The playlist has stopped.'
    else
      redirect_to @event, error: 'An error occurred stopping the playlist.'
    end
  end

  def create_new_playlist
    if create_playlist(true)
      redirect_to @event, notice: 'Slick! A new playlist was created.'
    else
      redirect_to @event, error: 'An error occurred creating the new playlist.'
    end
  end

  private

  def pnator_setup
    pnator_on = params[:pnator_on] == 'on'
    if pnator_on
      target_energy = params[:pnator_energy].to_i / 100.to_f
      target_danceability = params[:pnator_danceability].to_i / 100.to_f
      target_popularity = params[:pnator_popularity].to_i / 100.to_f
      target_speechiness = params[:pnator_speechiness].to_i / 100.to_f
      target_happiness = params[:pnator_happiness].to_i / 100.to_f

      @event.pnator_enabled = pnator_on
      @event.pnator_danceability = target_danceability
      @event.pnator_energy = target_energy
      @event.pnator_popularity = target_popularity
      @event.pnator_speechiness = target_speechiness
      @event.pnator_happiness = target_happiness
    end
  end

  def join_event_params
    if params.key?(:join_code)
      params[:join_code]
    elsif params.key?(:events) && params[:events].key?(:join_code)
      params[:events][:join_code]
    end
  end

  def set_playing
    @event.update!(currently_playing: true)
  end

  def queue_first_song
    @event.queue_next_song
  end

  def create_playlist(force = false)
    return true if @event.spotify_playlist_id.present? && !force

    playlist = @event.user.spotify.create_playlist!(@event.name)
    @event.update(spotify_playlist_id: playlist.id)
  end

  def set_join_cookie
    cookies.permanent.encrypted[:join_cookie] = @event.join_code
  end

  def set_user_identifier_cookie
    cookies.permanent[:user_identifier] = Digest::SHA1.hexdigest([Time.now.utc, rand].join)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :description, :join_code, :image_url)
  end

  def authenticate
    redirect_to root_path unless can_view?
  end

  def authenticate_owner
    redirect_to @event unless owns_event?
  end

  def can_view?
    (current_user.present? && @event.user == current_user) ||
      (Event.find_by_join_code(cookies.permanent.encrypted[:join_cookie]) == @event)
  end

  def owns_event?
    current_user.present? && @event.user == current_user
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true
module EventsHelper
end

app/views/events/_actions.html.haml
- if owner?(@event)
  - if !current_user.user_spotify_authenticated?
    = link_to '/auth/spotify', class: 'btn btn-primary' do
      %i.fa.fa-spotify
      Sign in with Spotify
  - else
    - if @event.currently_playing
      = link_to stop_playing_event_path, method: :post, class: 'btn btn-primary' do
        %i.fa.fa-stop
        Stop Playing on Spotify
    - elsif !@event.currently_playing && @event.spotify_playlist_id.present?
      = link_to start_playing_event_path, method: :post, class: 'btn btn-primary' do
        %i.fa.fa-play
        Play on Spotify

    - if @event.spotify_playlist_id.present?
      = link_to create_new_playlist_event_path, method: :post, class: 'btn btn-primary' do
        %i.fa.fa-spotify
        Create new Spotify Playlist
    - else
      = link_to create_new_playlist_event_path, method: :post, class: 'btn btn-primary' do
        %i.fa.fa-spotify
        Create Spotify Playlist

  - if @event.pnator_enabled
    = link_to '#pnator', class: 'btn btn-info' do
      %i.fa.fa-magic
      Magic Playlist
- elsif @event.user.user_spotify_authenticated? && @event.spotify_playlist_id.present?
  = link_to "https://open.spotify.com/user/#{@event.user.spotify_id}/playlist/#{@event.spotify_playlist_id}", class: 'btn btn-primary' do
    %i.fa.fa-play
    Play in browser
  = link_to "spotify:user:#{@event.user.spotify_id}:playlist:#{@event.spotify_playlist_id}", class: "btn btn-primary" do
    %i.fa.fa-play
    Play in Spotify

app/views/events/_form.html.haml
= form_for(event) do |f|

  - if event.errors.any?
    %div.alert.alert-danger
      %a.close{ 'data-dismiss': 'alert' }
        %i.fa.fa-times

      %strong
        = pluralize(event.errors.count, 'error')
        prohibited this event from being saved:

      %ul
        - event.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :name
    = f.text_field :name, autofocus: true, class: 'form-control', required: true

  .form-group
    = f.label :join_code
    = f.text_field :join_code, class: 'form-control', required: true
    %small.form-text.text-muted
      The join code must be lowercase alphanumeric and may include a dash (-) or underscore (_)

  .form-group
    = f.label :image_url
    = f.text_field :image_url, class: 'form-control', required: false
    %small.form-text.text-muted
      Should be a direct link to an image. Can be left blank for a default image.

  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control', required: true

  .form-group
    %label{ for: 'pnator_on' } Enable Playlistinator
    %input{ name: 'pnator_on', id: 'pnatorToggle', type: 'checkbox' }

  %div{ id: 'pnatorFields' }
    .form-group
      %label{ for: 'pnator_danceability' } Danceability
      %input{ name: 'pnator_danceability', type: 'text', 'data-provide': 'slider',
              'data-slider-min': 0, 'data-slider-max': 100, 'data-slider-value': 50 }

    .form-group
      %label{ for: 'pnator_energy' } Energy
      %input{ name: 'pnator_energy', type: 'text', 'data-provide': 'slider',
              'data-slider-min': 0, 'data-slider-max': 100, 'data-slider-value': 50 }

    .form-group
      %label{ for: 'pnator_popularity' } Popularity
      %input{ name: 'pnator_popularity', type: 'text', 'data-provide': 'slider',
              'data-slider-min': 0, 'data-slider-max': 100, 'data-slider-value': 50 }

    .form-group
      %label{ for: 'pnator_speechiness' } Speechiness
      %input{ name: 'pnator_speechiness', type: 'text', 'data-provide': 'slider',
              'data-slider-min': 0, 'data-slider-max': 100, 'data-slider-value': 50 }

    .form-group
      %label{ for: 'pnator_happiness' } Happiness
      %input{ name: 'pnator_happiness', type: 'text', 'data-provide': 'slider',
              'data-slider-min': 0, 'data-slider-max': 100, 'data-slider-value': 50 }

  = f.submit class: 'btn btn-primary'

app/views/events/edit.html.haml
.container.container-custom
  .row
    .col-md-8.offset-md-2
      %h2.header-brand
        Edit Event

      = render 'form', event: @event

      = link_to 'Cancel', @event, class: "btn btn-secondary"

      = link_to event_path(@event), method: :delete, class: "btn btn-danger pull-xs-right" do
        %i.fa.fa-trash
        Delete

app/views/events/new.html.haml
.container.container-custom
  .row
    .col-md-8.offset-md-2
      %h2.header-brand
        Host an Event

      %p
        If you want to host an event (party, gathering, etc) you first need
        to create an event. Afterwards, you'll be able to invite guests to collaborate.

      = render 'form', event: @event

      = link_to 'Cancel', current_user

app/views/events/show.html.haml
:javascript
  window.eventId = #{@event.id};
  window.currentUserIsOwner = #{@current_user.is_a?(User) && owner?(@event)}
  window.user_spotify_authed = #{@current_user.present? &&
    @current_user.spotify_attributes.present?}

.container.container-custom
  .row
    .col-md-12.col-lg-8.offset-lg-2

      - if owner?(@event)
        .card
          .card-block
            %p.card-text.lead
              Invite some guests to join! You can use any of the following methods.

            %ul
              %li
                Provide them with the event code
                %strong{ id: 'eventJoinCode' }
                  = @event.join_code
                and direct them to the
                = link_to 'landing page.', root_path

              %li
                Share this
                %a{ href: '#', id: 'eventQRPopover' }
                  %i.fa.fa-qrcode
                  QR Code
                with them.

              %li
                Or direct them to this link:
                = link_to "http://www.playthisfor.us#{join_events_path(join_code: @event.join_code)}", join_events_path(join_code: @event.join_code)


      .card
        .event__banner{ style: "background-image: url('#{image_url(@event.avatar_image)}')" }
          .event__banner-overlay
            .currently-playing__song

          %h2.event__name
            = @event.name

            - if owner?(@event)
              %small
                = link_to edit_event_path(@event), class: 'event__edit' do
                  %i.fa.fa-pencil
                  Edit
            - elsif @event.user.avatar.present? && @event.user.display_name.present?
              %small.event__owner
                Hosted by
                = image_tag(@event.user.avatar, class: 'user__avatar user__avatar--mini')
                = @event.user.display_name

        .card-block
          %p.card-text.lead
            = @event.description

        .card-footer.text-muted
          = render 'actions'
          %button.btn.btn-primary{"data-target" => "#intro-modal", "data-toggle" => "modal", :type => "button"}
            %i.fa.fa-question-circle
            How does this work?

  .row
    .col-md-12.col-lg-8.offset-lg-2
      %form.search-form
        .form-group
          .input-group
            .input-group-addon
              %i.fa.fa-search
            %input.form-control.form-control-lg.search-entry{ type: 'text', placeholder: 'Search for Songs on Spotify' }
            .input-group-addon.search-results__close
              %i.fa.fa-times
          .search-results

      .songs-list


.modal.fade#intro-modal
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        - if params[:is_guest]
          = link_to event_path(@event), class: 'close' do
            %span{"aria-hidden" => "true"} ×
        - else
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
        %h4.modal-title
          Hey! First time here?
      .modal-body
        %p.lead
          Here are a few tips to get started and collaborate on this event.
        %ol
          %li
            You can give one upvote (
            %i.fa.fa-chevron-up
            ) or one downvote (
            %i.fa.fa-chevron-down
            ) for each song
            in the playlist. You can change these at any time.
          %li
            The song with the most upvotes will be played next and removed
            from the top of the playlist queue.
          %li
            You can add your own songs by searching in the search bar. Other
            guests can then vote on your suggestions.
        .embed-responsive.embed-responsive-16by9
          %iframe{:allowfullscreen => "", :frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/BRjlNPWzjAc?rel=0&controls=0&showinfo=0&modestbranding=1", :width => "560"}
      .modal-footer
        - if params[:is_guest]
          = link_to event_path(@event), class: 'btn btn-primary' do
            Cool, let's play some music!
        - else
          %button.btn.btn-primary{"data-dismiss" => "modal", :type => "button"}
            Cool, Got it!


- if params[:is_guest]
  :javascript
    $(document).ready(function () {
      var visitedBefore = document.cookie.includes("VisitedBefore");

      if(!visitedBefore) {  // First time visitor
        $('#intro-modal').modal('show');
      }

      var expire = new Date();
      expire = new Date(expire.getTime() + 7776000000);

      document.cookie = "VisitedBefore=yes; expires=" + expire;
    });