config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # websocket
  mount ActionCable.server => '/cable'

  # landing page
  root 'home#index'

  # users and authentication
  devise_for :users
  resources :users, only: [:show]

  # spotify user oauth authentication
  get '/auth/spotify/callback', to: 'users#spotify'

  # events management and joining
  resources :events, except: [:index] do
    post 'start_playing', on: :member
    post 'stop_playing', on: :member
    post 'create_new_playlist', on: :member
  end

  get '/:join_code' => 'events#join', :as => :join_events
  post '/join' => 'events#join', :as => :join_events_submit
end

app/views/layouts/application.html.haml
%html
  %head
    %title
      Play This

    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = action_cable_meta_tag

    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}

  %body{ class: "#{yield (:body_class)}" }
    %nav.navbar.navbar-fixed-top.bg-custom
      .navbar-header
        %button.navbar-toggler.float-xs-right.hidden-md-up{ type: 'button', 'data-toggle': 'collapse', 'data-target': '#navContent' }
          %i.fa.fa-bars

        = link_to root_path, class: "navbar-brand" do
          %i.fa.fa-music
          Play This

      .collapse.navbar-toggleable-sm{id: 'navContent'}
        %ul.nav.navbar-nav.float-xs-right
          - if user_signed_in?
            %li.nav-item
              = link_to new_event_path, class: "nav-link" do
                %i.fa.fa-users
                Host an Event
            %li.nav-item
              = link_to user_path(current_user), class: "nav-link" do
                %i.fa.fa-user
                Profile
            %li.nav-item
              = link_to destroy_user_session_path, :method => :delete, class: "nav-link" do
                %i.fa.fa-sign-out
                Sign Out
          - else
            %li.nav-item
              = link_to new_user_session_path, class: "nav-link" do
                %i.fa.fa-sign-in
                Sign In
            %li.nav-item
              = link_to new_user_registration_path, class: "nav-link" do
                %i.fa.fa-user-plus
                Sign Up


    - unless flash.empty?
      .container.flash-container
        - flash.each do |name, msg|
          - if msg.is_a?(String)
            %div{ class: "alert alert-#{name == :notice.to_s ? "success" : "danger"} flash-display #{yield (:alert_class)}" }
              %a.close{ "data-dismiss": "alert" }
                %i.fa.fa-times
              = content_tag :div, msg, :id => "flash_#{name}"

    = yield

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-86726803-1', 'auto');
      ga('send', 'pageview');